export default function lookup(n) {
  const name = n.toLowerCase();
  return name in namesTable ? namesTable[name] : name;
}
const namesTable = {
  afghanistan: 'afghanistan',
  albania: 'albania',
  algeria: 'algerie',
  andorra: 'andorra',
  angola: 'angola',
  'antigua and barbuda': 'antigua og barbuda',
  argentina: 'argentina',
  armenia: 'armenia',
  australia: 'australia',
  austria: 'østerrike',
  azerbaijan: 'aserbajdsjan',
  bahamas: 'bahamas',
  bahrain: 'bahrain',
  bangladesh: 'bangladesh',
  barbados: 'barbados',
  belarus: 'hviterussland',
  belgium: 'belgia',
  belize: 'belize',
  benin: 'benin',
  bhutan: 'bhutan',
  bolivia: 'bolivia',
  'bosnia and herzegovina': 'bosnia-hercegovina',
  botswana: 'botswana',
  brazil: 'brasil',
  brunei: 'brunei',
  bulgaria: 'bulgaria',
  'burkina faso': 'burkina faso',
  burundi: 'burundi',
  cambodia: 'kambodsja',
  cameroon: 'kamerun',
  canada: 'canada',
  'cape verde': 'kapp verde',
  'central african republic': 'den sentralafrikanske republikk',
  chad: 'tsjad',
  chile: 'chile',
  china: 'kina',
  colombia: 'colombia',
  comoros: 'komorene',
  'costa rica': 'costa rica',
  'côte d’ivoire': 'elfenbenskysten',
  croatia: 'kroatia',
  cuba: 'cuba',
  cyprus: 'kypros',
  'czech republic': 'tsjekkia',
  'democratic republic of the congo': 'den demokratiske republikken kongo',
  denmark: 'danmark',
  djibouti: 'djibouti',
  dominica: 'dominica',
  'dominican republic': 'den dominikanske republikk',
  'east timor': 'øst-timor',
  ecuador: 'ecuador',
  egypt: 'egypt',
  'el salvador': 'el salvador',
  'equatorial guinea': 'ekvatorial-guinea',
  eritrea: 'eritrea',
  estonia: 'estland',
  ethiopia: 'etiopia',
  fiji: 'fiji',
  finland: 'finland',
  france: 'frankrike',
  gabon: 'gabon',
  gambia: 'gambia',
  georgia: 'georgia',
  germany: 'tyskland',
  ghana: 'ghana',
  greece: 'hellas',
  grenada: 'grenada',
  guatemala: 'guatemala',
  guinea: 'guinea',
  'guinea-bissau': 'guinea-bissau',
  guyana: 'guyana',
  haiti: 'haiti',
  honduras: 'honduras',
  hungary: 'ungarn',
  iceland: 'island',
  india: 'india',
  indonesia: 'indonesia',
  iran: 'iran',
  iraq: 'irak',
  ireland: 'irland',
  israel: 'israel',
  italy: 'italia',
  jamaica: 'jamaica',
  japan: 'japan',
  jordan: 'jordan',
  kazakhstan: 'kasakhstan',
  kenya: 'kenya',
  kiribati: 'kiribati',
  kuwait: 'kuwait',
  kyrgyzstan: 'kirgisistan',
  laos: 'laos',
  latvia: 'latvia',
  lebanon: 'libanon',
  lesotho: 'lesotho',
  liberia: 'liberia',
  libya: 'libya',
  liechtenstein: 'liechtenstein',
  lithuania: 'litauen',
  luxembourg: 'luxembourg',
  madagascar: 'madagaskar',
  malawi: 'malawi',
  malaysia: 'malaysia',
  maldives: 'maldivene',
  mali: 'mali',
  malta: 'malta',
  'marshall islands': 'marshalløyene',
  mauritania: 'mauritania',
  mauritius: 'mauritius',
  mexico: 'mexico',
  micronesia: 'mikronesia',
  moldova: 'moldova',
  monaco: 'monaco',
  mongolia: 'mongolia',
  montenegro: 'montenegro',
  morocco: 'marokko',
  mozambique: 'mosambik',
  myanmar: 'myanmar',
  namibia: 'namibia',
  nauru: 'nauru',
  nepal: 'nepal',
  netherlands: 'nederland',
  'new zealand': 'new zealand',
  nicaragua: 'nicaragua',
  niger: 'niger',
  nigeria: 'nigeria',
  'north korea': 'nord-korea',
  'korea, north': 'nord-korea',
  norway: 'norge',
  oman: 'oman',
  pakistan: 'pakistan',
  palau: 'palau',
  panama: 'panama',
  'papua new guinea': 'papua ny-guinea',
  paraguay: 'paraguay',
  peru: 'peru',
  philippines: 'filippinene',
  poland: 'polen',
  portugal: 'portugal',
  qatar: 'qatar',
  'republic of the congo': 'republikken kongo',
  'republic of macedonia': 'republikken makedonia',
  romania: 'romania',
  russia: 'russland',
  rwanda: 'rwanda',
  'saint kitts and nevis': 'saint kitts og nevis',
  'saint lucia': 'saint lucia',
  'saint vincent and the grenadines': 'saint vincent og grenadinene',
  samoa: 'samoa',
  'san marino': 'san marino',
  'sao tome and principe': 'são tomé og príncipe',
  'saudi arabia': 'saudi-arabia',
  senegal: 'senegal',
  serbia: 'serbia',
  seychelles: 'seychellene',
  'sierra leone': 'sierra leone',
  singapore: 'singapore',
  slovakia: 'slovakia',
  slovenia: 'slovenia',
  'solomon islands': 'salomonøyene',
  somalia: 'somalia',
  'south africa': 'Sør-Afrika',
  'south korea': 'Sør-Korea',
  'korea, south': 'Sør-Korea',
  'south sudan': 'Sør-Sudan',
  spain: 'spania',
  'sri lanka': 'sri lanka',
  sudan: 'sudan',
  suriname: 'surinam',
  swaziland: 'swaziland',
  sweden: 'sverige',
  switzerland: 'sveits',
  syria: 'syria',
  tajikistan: 'tadsjikistan',
  'taiwan*': 'taiwan',
  tanzania: 'tanzania',
  thailand: 'thailand',
  togo: 'togo',
  tonga: 'tonga',
  'trinidad and tobago': 'trinidad og tobago',
  tunisia: 'tunisia',
  turkey: 'tyrkia',
  turkmenistan: 'turkmenistan',
  tuvalu: 'tuvalu',
  uganda: 'uganda',
  ukraine: 'ukraina',
  'united arab emirates': 'de forente arabiske emirater',
  'united kingdom': 'storbritannia',
  'united states of america': 'USA',
  us: 'USA',
  'united states': 'USA',
  uruguay: 'uruguay',
  uzbekistan: 'usbekistan',
  vanuatu: 'vanuatu',
  venezuela: 'venezuela',
  vietnam: 'vietnam',
  yemen: 'jemen',
  zambia: 'zambia',
  zimbabwe: 'zimbabwe'
};
